# terminal / 256-color
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# panes
bind v split-window -h
bind h split-window -v
unbind '"'
unbind %
bind -n C-M-j select-pane -t :.+

# reload config
bind r source-file ~/.config/tmux/.tmux.conf \; display-message "config reloaded!"

# mouse + escape
set -g mouse on
set escape-time 0

# status bar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=red'
set -g status-left ''
set -g status-left-length 10
set -g status-right-style 'fg=black bg=yellow'
set -g status-right '%Y-%m-%d %H:%M '
set -g status-right-length 50

# window styles
setw -g window-status-current-style 'fg=black bg=red'
setw -g window-status-current-format ' #I #W #F '
setw -g window-status-style 'fg=red bg=black'
setw -g window-status-format ' #I #[fg=white]#W #[fg=yellow]#F '
setw -g window-status-bell-style 'fg=yellow bg=red bold'

# pane borders
set -g pane-border-style fg=white
set -g pane-active-border-style fg=green

# messages
set -g message-style 'fg=yellow bg=red bold'
